# Generated by Django 2.2.7 on 2020-03-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_cust'),
    ]

    operations = [
        migrations.CreateModel(
            name='campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('img', models.FileField(upload_to='photo')),
                ('desc', models.TextField()),
            ],
        ),
    ]
