# Generated by Django 2.2.7 on 2020-03-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='img',
            field=models.FileField(upload_to='pics'),
        ),
    ]
