# Generated by Django 2.2.7 on 2020-03-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_hackersclub_donater_redcross_donater'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodmanagement',
            name='phone_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
