# Generated by Django 2.2.7 on 2020-03-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_bloodmanagement_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodmanagement',
            name='last_name',
        ),
    ]
