# Generated by Django 2.2.7 on 2020-03-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_remove_bloodmanagement_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='hackersclub_donater',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='redcross_donater',
            name='last_name',
        ),
        migrations.AddField(
            model_name='cust',
            name='phone_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
