# Generated by Django 2.2.7 on 2020-03-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_auto_20200310_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='ku_redcross',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age1', models.IntegerField()),
                ('blood_group', models.TextField()),
                ('phone_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
